layout = "default"

[output]
show_os = true
show_cpu = true
show_memory = true
show_disk = true
show_uptime = true
show_cpu_model = true
show_gpu_model = true
show_kernel_version = true
show_display_server = true
show_desktop_environment = true
show_username = true
show_hostname = true
show_disks = true

info_keys = [
    "OS",
    "Kernel Version",
    "Desktop Environment",
    "Display Server",
    "Uptime",
    "CPU Model",
    "Memory",
    "GPU Model",
    "Username",
    "Hostname",
    "Disks"
]

[customization]
color_scheme = "dark"
font_size = 12
alignment = "left"

[colors]
# Dark Modern Palette - Elegant and Professional
OS = "#E06C75"  # Soft Red
Username = "#98C379"  # Soft Green
Hostname = "#E5C07B"  # Soft Yellow
"Desktop Environment" = "#C678DD"  # Soft Purple
Memory = "#56B6C2"  # Soft Cyan
Disks = "#FF6B6B"  # Bright Red
"CPU Model" = "#61AFEF"  # Soft Blue
"GPU Model" = "#FFA07A"  # Light Salmon
"Kernel Version" = "#ABB2BF"  # Light Grey
"Display Server" = "#4ECDC4"  # Turquoise
Uptime = "#F8BBD9"  # Light Pink

[symbols]
OS = "\U0001f5a5\ufe0f"
Username = "\U0001f464"
Hostname = "\U0001f4e1"
"Desktop Environment" = "\U0001f320"
Memory = "\U0001f4be"
Disks = "\U0001f4c2"
"CPU Model" = "\U0001f9ea"
"GPU Model" = "\U0001f5a8\ufe0f"
"Kernel Version" = "\U0001f4bb"
"Display Server" = "\U0001f5b1\ufe0f"
Uptime = "\U000023F0"
