layout = "default"

[output]
show_os = true
show_cpu = true
show_memory = true
show_disk = true
show_uptime = true

info_keys = [
    "OS",
    "Kernel Version",
    "Desktop Environment",
    "Display Server",
    "CPU Model",
    "Memory",
    "GPU Model",
    "Username",
    "Hostname",
    "Disks"
]

[customization]
color_scheme = "default"
font_size = 12
alignment = "left"

[colors]
OS = "#1E90FF"  # Dodger Blue
Username = "#32CD32"  # Lime Green
Hostname = "#FFD700"  # Gold
"Desktop Environment" = "#FF69B4"  # Hot Pink
Memory = "#00FA9A"  # Medium Spring Green
Disks = "#FF4500"  # Orange Red
"CPU Model" = "#8A2BE2"  # Blue Violet
"GPU Model" = "#7FFF00"  # Chartreuse
"Kernel Version" = "#FF6347"  # Tomato
"Display Server" = "#4682B4"  # Steel Blue

[symbols]
OS = "\U0001f5a5\ufe0f"
Username = "\U0001f464"
Hostname = "\U0001f4e1"
"Desktop Environment" = "\U0001f320"
Memory = "\U0001f4be"
Disks = "\U0001f4c2"
"CPU Model" = "\U0001f9ea"
"GPU Model" = "\U0001f5a8\ufe0f"
"Kernel Version" = "\U0001f4bb"
"Display Server" = "\U0001f5b1\ufe0f"