layout = "default"

[output]
show_os = true
show_cpu = true
show_memory = true
show_disk = true
show_uptime = true
show_cpu_model = true
show_gpu_model = true
show_kernel_version = true
show_display_server = true
show_desktop_environment = true
show_username = true
show_hostname = true
show_disks = true

info_keys = [
    "OS",
    "Kernel Version",
    "Desktop Environment",
    "Display Server",
    "Uptime",
    "CPU Model",
    "Memory",
    "GPU Model",
    "Username",
    "Hostname",
    "Disks"
]

[customization]
color_scheme = "pastel"
font_size = 12
alignment = "left"

[colors]
# Modern Pastel Palette - Soft and Elegant
OS = "#FFB3BA"  # Soft Pink
Username = "#BAFFC9"  # Soft Mint
Hostname = "#FFFFBA"  # Soft Yellow
"Desktop Environment" = "#E8BAFF"  # Soft Lavender
Memory = "#BAE1FF"  # Soft Blue
Disks = "#FFB3D9"  # Soft Rose
"CPU Model" = "#B8E6B8"  # Soft Sage
"GPU Model" = "#FFD4B3"  # Soft Peach
"Kernel Version" = "#D4D4D4"  # Soft Grey
"Display Server" = "#B3E6FF"  # Soft Sky Blue
Uptime = "#FFE6B3"  # Soft Cream

[symbols]
OS = "\U0001f5a5\ufe0f"
Username = "\U0001f464"
Hostname = "\U0001f4e1"
"Desktop Environment" = "\U0001f320"
Memory = "\U0001f4be"
Disks = "\U0001f4c2"
"CPU Model" = "\U0001f9ea"
"GPU Model" = "\U0001f5a8\ufe0f"
"Kernel Version" = "\U0001f4bb"
"Display Server" = "\U0001f5b1\ufe0f"
Uptime = "\U000023F0"
