name: Build and Release Debian Packages

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build Debian package
        run: |
          cargo build --release --target=${{ matrix.target }}
          cargo deb --no-build --target=${{ matrix.target }}

      - name: Rename and move .deb file
        run: |
          mkdir -p artifacts
          arch_name="${{ matrix.target }}"
          arch_short=$(echo $arch_name | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/' | sed 's/-unknown-linux-gnu//')
          cp target/${{ matrix.target }}/debian/*.deb artifacts/piko_${arch_short}.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: artifacts/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
